Feature/7 sign in api
dilyara4949/flight-booking-api pull request #14
Opened 2024-07-15 07:22 UTC by dilyara4949

Added new api sign in, which returns access token and user if  user email and password are found, else returns error message

2024-07-15 10:44 UTC, MihailGorelikov requested changes

2024-07-15 10:44 UTC, MihailGorelikov commented on internal/handler/auth.go
> +		user, err := userService.ValidateUser(c, req)
any reason to return pointer here?

2024-07-15 10:44 UTC, MihailGorelikov commented on internal/repository/errors/errors.go
> +	ErrIncorrectPassword = errors.New("password is not correct")
invalid username name or password

2024-07-17 08:02 UTC, dilyara4949 commented on internal/handler/response/signin.go
> +	User        User   `json:"user"`
was not sure, should i return user info, did it in case if front will need it

2024-07-22 09:55 UTC, krylphi approved these changes
LGTM

2024-07-22 09:58 UTC, merged